### ISSUE TITLE
How is the project licensed?

### ISSUE THREAD

**Issue by mpenning** [favoretti/accessninja#3]
Just a simple question... How is the project licensed?

**Comment by favoretti** [comment]
Hey Mike,

Heh, never thought of it. MIT, I'll add a license file once I reach a computer. 

Regards,
Vlad

**Comment by favoretti** [comment]
Why BTW? You wanna help expand it or use elsewhere? :) (just curiosity here)

**Comment by mpenning** [comment]
I definitely want to try it out... I am not opposed to contributing, but I should start with unit tests and see how much time I have to give.

**Comment by favoretti** [comment]
Added LICENSE file with MIT in it.
